# Your Discord bot token used for logging in.
token = ""
# The bot extensions to load on startup.
extensions = [
    "jishaku",
    "extensions.tags",

]
# Postgres database connection.
[database]
connection_uri = ""
#Logging settings.
[logging]
webhook_url = ""
logging_level = "WARNING"
bot_name ="leaf"



